# Generated by Django 6.0.3 on 2026-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('lab', 'Lab'), ('organisation', 'Organisation'), ('viewer', 'Viewer'), ('independent', 'Independent Researcher')], default='viewer', max_length=20),
        ),
    ]
