# Generated by Django 6.0.3 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_orcid_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('lab', 'Lab'), ('organisation', 'Organisation'), ('viewer', 'Viewer'), ('independent', 'Independent Researcher'), ('admin', 'Admin')], default='viewer', max_length=20),
        ),
    ]
