# Generated by Django 6.0.3 on 2026-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archive_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('subscription_expired', 'Subscription Expired'), ('subscription_not_renewed', 'Subscription Not Renewed'), ('subscription_removed', 'Subscription Removed'), ('security_violation', 'Security Violation'), ('harmful_content', 'Harmful / Abusive Content'), ('terms_violation', 'Terms of Service Violation'), ('fraud', 'Fraudulent Activity'), ('inactivity', 'Extended Inactivity'), ('admin_decision', 'Administrative Decision'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
