# Generated by Django 6.0.5 on 2026-05-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_archive_message_user_archive_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('sky', 'Sky'), ('violet', 'Violet'), ('blue', 'Blue'), ('amber', 'Amber'), ('rose', 'Rose'), ('orange', 'Orange'), ('indigo', 'Indigo')], default='slate', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
