# Generated by Django 6.0.3 on 2026-05-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('research', 'Research'), ('experiment', 'Experiment'), ('conference', 'Conference'), ('meeting', 'Meeting'), ('writing', 'Writing'), ('submission', 'Submission'), ('milestone', 'Milestone'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('active', 'In Progress'), ('done', 'Done')], default='todo', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['start_date', 'created_at'],
            },
        ),
    ]
