# Generated by Django 6.0.5 on 2026-05-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_savedcomparison'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedComparison',
        ),
    ]
