# Generated by Django 6.0.3 on 2026-04-12 10:21

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='papers/')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PaperChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_number', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.paper')),
            ],
        ),
    ]
