# Generated by Django 6.0.3 on 2026-05-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperasset',
            name='asset_type',
            field=models.CharField(choices=[('pdf', 'PDF document'), ('image', 'Embedded image'), ('other', 'Other')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('note', 'Quick Note'), ('link', 'Web Link'), ('video', 'Video'), ('file', 'File / Attachment'), ('quote', 'Quote / Excerpt')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('r2_key', models.TextField(blank=True)),
                ('file_url', models.TextField(blank=True)),
                ('file_name', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_items', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
