# Generated by Django 6.0.3 on 2026-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paperasset_asset_type_alter_paper_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('research', 'Research Paper'), ('literature_review', 'Literature Review'), ('notes', 'Research Notes'), ('reference_notes', 'Reference Notes'), ('conference_notes', 'Conference Notes'), ('meeting_notes', 'Meeting Notes'), ('experiment_log', 'Experiment Log'), ('technical_doc', 'Technical Documentation'), ('proposal', 'Proposal'), ('thesis', 'Thesis'), ('dataset_doc', 'Dataset Documentation')], default='notes', max_length=50),
        ),
    ]
