# Generated by Django 6.0.5 on 2026-05-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citation_format',
            field=models.CharField(choices=[('ieee', 'IEEE'), ('apa', 'APA 7th'), ('mla', 'MLA 9th'), ('chicago', 'Chicago 17th'), ('vancouver', 'Vancouver'), ('harvard', 'Harvard')], default='ieee', max_length=20),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='doi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='journal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='pages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
