# Generated by Django 6.0.5 on 2026-05-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_paper_citation_format_referenceitem_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperchunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paperchunk',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
